services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data
    restart: unless-stopped
    env_file: server.env
    ports:
      - "80:5000"
    links:
      - "postgresDb:postgresDb"
      - "redisCaching:redisCaching"
    depends_on:
      - postgresDb
      - redisCaching
  init:
    build:
      context: .
      dockerfile: ./init/Dockerfile
    container_name: init
    env_file: server.env
    links:
      - "postgresDb:postgresDb"
    depends_on:
      - postgresDb
  postgresDb:
    image: postgres:latest
    container_name: postgresDb
    ports:
      - "5432:5432"
    env_file: db.env
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redisCaching
    env_file: redis.env
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}",
      "--port", "6379"
    ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
