name: Server CI

on: 
  pull_request:
    paths:
      app/server/**
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/server/requirements.txt
    - name: Run Script
      run: |
        sh scripts/coverage_python.sh
    - name: Upload test report 
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/server/htmlcov/index.html
